### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GenryMg** [1mgr007/discord-musicbot-addon#1]
Got this error when using this module, do you know why?

```Error: could not defineProperty(s) musicArraySort or musicBotShuffle, you are likely running this script twice. actual error: TypeError: Cannot redefine property: musicArraySort at Function.defineProperty (<anonymous>) at Object.exports.start (/rbd/pnpm-volume/b61a9277-9cdc-4324-bb15-59d6b9a53b28/node_modules/.registry.npmjs.org/discord.js-musicbot-addon/13.9.1/node_modules/discord.js-musicbot-addon/index.js:1595:14) at Client.client.on (/app/index.js:832:16) at Client.emit (events.js:198:15) at MessageCreateHandler.handle (/rbd/pnpm-volume/b61a9277-9cdc-4324-bb15-59d6b9a53b28/node_modules/.registry.npmjs.org/discord.js/11.6.4/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34) at WebSocketPacketManager.handle (/rbd/pnpm-volume/b61a9277-9cdc-4324-bb15-59d6b9a53b28/node_modules/.registry.npmjs.org/discord.js/11.6.4/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65) at WebSocketConnection.onPacket (/rbd/pnpm-volume/b61a9277-9cdc-4324-bb15-59d6b9a53b28/node_modules/.registry.npmjs.org/discord.js/11.6.4/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35) at WebSocketConnection.onMessage (/rbd/pnpm-volume/b61a9277-9cdc-4324-bb15-59d6b9a53b28/node_modules/.registry.npmjs.org/discord.js/11.6.4/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17) at WebSocket.onMessage (/rbd/pnpm-volume/b61a9277-9cdc-4324-bb15-59d6b9a53b28/node_modules/.registry.npmjs.org/ws/6.2.1/node_modules/ws/lib/event-target.js:120:16) at WebSocket.emit (events.js:193:13) at Object.exports.start (/rbd/pnpm-volume/b61a9277-9cdc-4324-bb15-59d6b9a53b28/node_modules/.registry.npmjs.org/discord.js-musicbot-addon/13.9.1/node_modules/discord.js-musicbot-addon/index.js:1609:13) at Client.client.on (/app/index.js:832:16) at Client.emit (events.js:198:15) at MessageCreateHandler.handle (/rbd/pnpm-volume/b61a9277-9cdc-4324-bb15-59d6b9a53b28/node_modules/.registry.npmjs.org/discord.js/11.6.4/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34) at WebSocketPacketManager.handle (/rbd/pnpm-volume/b61a9277-9cdc-4324-bb15-59d6b9a53b28/node_modules/.registry.npmjs.org/discord.js/11.6.4/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65) at WebSocketConnection.onPacket (/rbd/pnpm-volume/b61a9277-9cdc-4324-bb15-59d6b9a53b28/node_modules/.registry.npmjs.org/discord.js/11.6.4/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35) at WebSocketConnection.onMessage (/rbd/pnpm-volume/b61a9277-9cdc-4324-bb15-59d6b9a53b28/node_modules/.registry.npmjs.org/discord.js/11.6.4/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17) at WebSocket.onMessage (/rbd/pnpm-volume/b61a9277-9cdc-4324-bb15-59d6b9a53b28/node_modules/.registry.npmjs.org/ws/6.2.1/node_modules/ws/lib/event-target.js:120:16) at WebSocket.emit (events.js:193:13) at Receiver.receiverOnMessage (/rbd/pnpm-volume/b61a9277-9cdc-4324-bb15-59d6b9a53b28/node_modules/.registry.npmjs.org/ws/6.2.1/node_modules/ws/lib/websocket.js:789:20) ```

**Comment by GenryMg** [comment]
I'm using the "basic" version on the example page. Just wanted to test the module out.

**Comment by 1mgr007** [comment]
Did you use this module ?
After I saw your problem, I thought you were using the [discord.js-musicbot-addon](https://www.npmjs.com/package/discord.js-musicbot-addon) module.
Because there was written error in [(/rbd/pnpm-volume/b61a9277-9cdc-4324-bb15-59d6b9a53b28/node_modules/.registry.npmjs.org/discord.js-musicbot-addon/13.9.1/node_modules/discord.js-musicbot-addon/index.js:1595:14)].
My module is [discord-musicbot-addon](https://www.npmjs.com/package/discord-musicbot-addon).

**Comment by GenryMg** [comment]
oh ok, ill check
